DROP TABLE IF EXISTS USER_CONNECTIONS;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE TRANSACTIONS (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sender INT NOT NULL,
    receiver INT NOT NULL,
    description VARCHAR(255),
    amount DOUBLE NOT NULL,
    CONSTRAINT fk_transactions_sender
        FOREIGN KEY (sender) REFERENCES USERS(id),
    CONSTRAINT fk_transactions_receiver
        FOREIGN KEY (receiver) REFERENCES USERS(id)
);

CREATE TABLE USER_CONNECTIONS (
    user_id INT NOT NULL,
    connection_id INT NOT NULL,
    PRIMARY KEY (user_id, connection_id),
    CONSTRAINT fk_user
        FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT fk_connection
        FOREIGN KEY (connection_id) REFERENCES USERS(id) ON DELETE CASCADE
);
